services:
  database:
    image: postgres:15.4-alpine
    restart: unless-stopped
    env_file: ./env/development-postgres.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database:
